### ISSUE TITLE
24H2

### ISSUE THREAD

**Issue by vmv** [MatiDEV-PL/Clean-Windows#1]
Not working with Windows 11, version 24H2 (26100.1150).
"Windows installation failed."

- https://uupdump.net/known.php?q=category:w11-24h2

**Comment by MatiDEV-PL** [comment]
Couldn't replicate the error on my part. Windows 11 24H2 (26100.1150) installed just fine.

![test](https://github.com/user-attachments/assets/24314d67-faae-4674-9d6a-6031b9b61b6c)

**Comment by vmv** [comment]
I have tested on a laptop that has only wireless network .. maybe that was the problem.
I have removed the Edge removal and those browsers install.. and it worked fine.

**Comment by MatiDEV-PL** [comment]
I tested again without any internet access and the installation proceeded without any issues. Windows 11 24H2 (26100.1150)

**Comment by vmv** [comment]
[autounattend.zip](https://github.com/user-attachments/files/16189676/autounattend.zip)
This is the working .xml
The error happened on copy stage, at around 40%-45% 
Tried 2 times, same error.

**Comment by MatiDEV-PL** [comment]
Cannot replicate this behavior. Maybe it's related to a hardware issue. Closed.

**Comment by MatiDEV-PL** [comment]
Cannot replicate this behavior. Maybe it's related to a hardware issue. Closed.

**Comment by MatiDEV-PL** [comment]
Cannot replicate this behavior. Maybe it's related to a hardware issue. Closed.
